### ISSUE TITLE
out of date with current wlroots

### ISSUE THREAD

**Issue by valpackett** [topisani/tablecloth#2]
The git revision mentioned in submodules doesn't exist in the wlroots repo, and building with current master fails (a lot of "no matching function" etc.)

---

btw, I'm also working on [a GTK/C++ DE for Wayland](https://github.com/myfreeweb/numbernine), currently based on modified Weston with a layer-shell plugin, but I'm thinking about switching to a wlroots based compositor because wlroots is more actively developed. I have a background image, a bar, a notification daemon, a Spotlight-like launcher, starting to build settings:

![pic of input settings](https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/n9-settings-input.png)

and planning to have a lockscreen and a polkit agent.

tablecloth sounds like a good compositor option for this :)

**Comment by topisani** [comment]
Its been some time since ive had time to update it, but thanks for the heads up. Still using it as my daily driver, so its by no means dead.

Id love for tablecloth to be integrated with `numbernine, numbernine, numbernine`, and while its not extremely versatile yet, i think the C++ codebase is one of the nicer ones.

I have a very simple lockscreen, and a notification manager. The bar desperately needs indicators support, and i need a system for changing configs on the fly. But this is a sideproject of mine, so its going a bit slow

**Comment by valpackett** [comment]
Yeah, on the fly configuration is one of my priorities. My current "solution" is the [compositor management protocol](https://github.com/myfreeweb/weston-extra-dip/blob/master/protocols/wldip-compositor-manager.xml):

- the whole configuration/state of the compositor (currently primarily libinput options) is serialized with [a flatbuffers schema](https://github.com/myfreeweb/weston-extra-dip/blob/master/schemas/Management.fbs)
- clients can get that state on demand or subscribe to get it when something happens (new input device plugged in, etc)
- and there's a bunch of requests for changing things — mostly just RPC to libinput functions :) but I also hacked weston to be able to change display scale on the fly

**Comment by topisani** [comment]
Seams reasonable to implement - wanna join forces a bit on this project?

**Comment by valpackett** [comment]
Yeah, of course. I'll start looking into the code soon.

In general, my compositor wishlist is:

- plugin system like in Weston (headers are installed, user-provided list of shared libs is `dlopen`ed at startup and initialization is called for each lib, plus plugins can export APIs to each other) (and some of the following items can be plugins)
- either a "security module" API that would allow a plugin to do access control for privileged protocols like layer-shell, or [capability based security](https://github.com/myfreeweb/weston-extra-dip/blob/master/protocols/wldip-capabilities.xml) being the one built-in security module
- ability to do [layered screenshots](https://github.com/myfreeweb/weston-extra-dip/blob/master/schemas/Screenshot.fbs) i.e. to individually export buffers from the renderer (I wonder if this needs support on the wlroots side or just here)
- some flexible way of handling keybindings – my settings daemon should be able to fully control them
- support for [xcape style keybinds](https://github.com/myfreeweb/weston-extra-dip/blob/master/key-modifier-binds.cpp) (e.g. press control on its own to get escape)
- ability to change display scale on the fly

**Comment by valpackett** [comment]
It's alive!! I've had to fix my incorrect usage of layer-shell but most things work now :D

![on-tablecloth](https://user-images.githubusercontent.com/208340/51183794-63a65a00-18e3-11e9-9187-00ff60fc9b25.png)

**Comment by valpackett** [comment]
Sooo.. I found Wayfire and realized it's exactly what I've been looking for. Sorry, but tablecloth won't be the numbernine compositor.
